### ISSUE TITLE
How to create new dataset

### ISSUE THREAD

**Issue by eL-Prova** [mazen160/secrets-patterns-db#11]
Hi @mazen160,

How can we create new datasets? So the rules-stable.yml will be updated with the resources.
You have on your blog only the way how to create an export for GitLeaks or TruffleHog (this missing in the MD of readonly :-) )

Kind regards

**Comment by mazen160** [comment]
Hi @eL-Prova

The datasets folder is just to store raw data that can be used to generate the rules-stable.yml. The process is done manually, however, the process of exporting rules-stable.yml to GitLeaks or Trufflehog is done with the scripts within this repository.
