### ISSUE TITLE
BBOT Integration

### ISSUE THREAD

**Issue by TheTechromancer** [mazen160/secrets-patterns-db#3]
Awesome work on this repo! 

I have integrated this into a [new BBOT module](https://github.com/blacklanternsecurity/bbot/blob/secrets-patterns-db-2/bbot/modules/secretsdb.py), and the results look very promising. The module enables `secrets-patterns-db` to search web page content (html, `.js` files, etc.) across an organization's entire attack surface.

The main challenge is weeding out the false positives. Right now there are quite a few of these, as you can see even by running the BBOT module against `www.example.com`:

```bash
git clone -b secrets-patterns-db https://github.com/blacklanternsecurity/bbot && cd bbot
pip install poetry; poetry install; poetry shell

bbot -m secrets -t http://www.example.com
```

We at Black Lantern would love to contribute to this repo. Would you be interested in working with us to find a solution to the false positives? Our first thought was to maintain a sort of blacklist. This would be simple but difficult to maintain. A more advanced approach might involve deep learning, such as what the guys at Praetorian did with Nosey Parker (sadly they did not open source their machine learning stuff):

![image](https://user-images.githubusercontent.com/20261699/217630377-956b54ef-238d-440f-a885-b4464d5642cf.png)

EDIT: I made a PR: https://github.com/mazen160/secrets-patterns-db/pull/4

Again, great work on this, and curious to hear your thoughts!

**Comment by mazen160** [comment]
Hi @TheTechromancer, 

Amazing work again, I'm definitely happy to collaborate into getting better confidence levels across the patterns to reduce the FP rate. The approach that you have taken sounds great, I will be trying to get it tested and merged some time next week.

Thank you!

Best Regards,
Mazin

**Comment by mazen160** [comment]
PR and code are merged! Thank you again for the excellent contribution!

If you have more ideas on improving the repo, feel free to open new tickets or email me directly!
